/** \file
 *  This C source file was generated by $ANTLR version 3.1.3 Mar 18, 2009 10:09:25
 *
 *     -  From the grammar source file : ubibind.g
 *     -                            On : 2017-06-07 13:36:55
 *     -                for the parser : ubibindParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

	extern "C++" {
		#include <fstream>
//		#include "Tools.hpp"
		#include "UbibindDefs.hpp"
		#include "BindSources.hpp"
	}
	#include <stdlib.h>

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ubibindParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pubibindParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pubibindParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pubibindParser_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ubibindParserTokenNames[24+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "IDENTIFIER",
        (pANTLR3_UINT8) "RAW_DEFINITION",
        (pANTLR3_UINT8) "INTEGER_LITERAL",
        (pANTLR3_UINT8) "REAL_LITERAL",
        (pANTLR3_UINT8) "ESCAPE_SEQUENCE",
        (pANTLR3_UINT8) "CHARACTER_LITERAL",
        (pANTLR3_UINT8) "STRING_LITERAL",
        (pANTLR3_UINT8) "BOOLEAN_LITERAL",
        (pANTLR3_UINT8) "LETTER",
        (pANTLR3_UINT8) "DIGIT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "LINE_COMMENT",
        (pANTLR3_UINT8) "'%module'",
        (pANTLR3_UINT8) "'%linkerlibs'",
        (pANTLR3_UINT8) "'='",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'%typemap'",
        (pANTLR3_UINT8) "'in'",
        (pANTLR3_UINT8) "'out'",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "','"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static void	compilation_unit    (pubibindParser ctx, SParamOptions options);
static void	module_declaration    (pubibindParser ctx);
static void	raw_definition    (pubibindParser ctx);
static void	linker_libs_definition    (pubibindParser ctx);
static void	typemap    (pubibindParser ctx);
static void	interface_definition    (pubibindParser ctx);
static void	function_definition    (pubibindParser ctx);
static void	parameters_list    (pubibindParser ctx, std::vector<std::string> &parameters);
static ubibindParser_param_definition_return	param_definition    (pubibindParser ctx);
static ubibindParser_type_return	type    (pubibindParser ctx);
static void	ubibindParserFree(pubibindParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ubibind.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ubibindParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pubibindParser
ubibindParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ubibindParserNewSSD(instream, NULL);
}

/** \brief Create a new ubibindParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pubibindParser
ubibindParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pubibindParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pubibindParser) ANTLR3_CALLOC(1, sizeof(ubibindParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in ubibindParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ubibindParser interface
     */
    ctx->compilation_unit	= compilation_unit;
    ctx->module_declaration	= module_declaration;
    ctx->raw_definition	= raw_definition;
    ctx->linker_libs_definition	= linker_libs_definition;
    ctx->typemap	= typemap;
    ctx->interface_definition	= interface_definition;
    ctx->function_definition	= function_definition;
    ctx->parameters_list	= parameters_list;
    ctx->param_definition	= param_definition;
    ctx->type	= type;
    ctx->free			= ubibindParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

    /* Create a LIST for recording rule memos.
     */
     RULEMEMO    = antlr3IntTrieNew(15);	/* 16 bit depth is enough for 32768 rules! */
	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ubibindParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 ubibindParserFree(pubibindParser ctx)
 {
    /* Free any scope memory
     */
    
        
	if	(RULEMEMO != NULL)
	{
		RULEMEMO->free(RULEMEMO);
		RULEMEMO = NULL;
	}	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return ubibindParserTokenNames; 
}


    	CBindSources bindSource;
    	#define GETTEXT(token) std::string((const char*)(token->getText(token))->chars)

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_module_declaration_in_compilation_unit112  */
static	ANTLR3_BITWORD FOLLOW_module_declaration_in_compilation_unit112_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_module_declaration_in_compilation_unit112	= { FOLLOW_module_declaration_in_compilation_unit112_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_raw_definition_in_compilation_unit115  */
static	ANTLR3_BITWORD FOLLOW_raw_definition_in_compilation_unit115_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000240010) };
static  ANTLR3_BITSET_LIST FOLLOW_raw_definition_in_compilation_unit115	= { FOLLOW_raw_definition_in_compilation_unit115_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_linker_libs_definition_in_compilation_unit119  */
static	ANTLR3_BITWORD FOLLOW_linker_libs_definition_in_compilation_unit119_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200010) };
static  ANTLR3_BITSET_LIST FOLLOW_linker_libs_definition_in_compilation_unit119	= { FOLLOW_linker_libs_definition_in_compilation_unit119_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_typemap_in_compilation_unit128  */
static	ANTLR3_BITWORD FOLLOW_typemap_in_compilation_unit128_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200010) };
static  ANTLR3_BITSET_LIST FOLLOW_typemap_in_compilation_unit128	= { FOLLOW_typemap_in_compilation_unit128_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_interface_definition_in_compilation_unit134  */
static	ANTLR3_BITWORD FOLLOW_interface_definition_in_compilation_unit134_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_interface_definition_in_compilation_unit134	= { FOLLOW_interface_definition_in_compilation_unit134_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_compilation_unit139  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_compilation_unit139_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_compilation_unit139	= { FOLLOW_EOF_in_compilation_unit139_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_module_declaration158  */
static	ANTLR3_BITWORD FOLLOW_17_in_module_declaration158_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_module_declaration158	= { FOLLOW_17_in_module_declaration158_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_module_declaration160  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_module_declaration160_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_module_declaration160	= { FOLLOW_IDENTIFIER_in_module_declaration160_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RAW_DEFINITION_in_raw_definition178  */
static	ANTLR3_BITWORD FOLLOW_RAW_DEFINITION_in_raw_definition178_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RAW_DEFINITION_in_raw_definition178	= { FOLLOW_RAW_DEFINITION_in_raw_definition178_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_linker_libs_definition196  */
static	ANTLR3_BITWORD FOLLOW_18_in_linker_libs_definition196_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_linker_libs_definition196	= { FOLLOW_18_in_linker_libs_definition196_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_linker_libs_definition198  */
static	ANTLR3_BITWORD FOLLOW_19_in_linker_libs_definition198_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_linker_libs_definition198	= { FOLLOW_19_in_linker_libs_definition198_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_linker_libs_definition201  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_linker_libs_definition201_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100010) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_linker_libs_definition201	= { FOLLOW_IDENTIFIER_in_linker_libs_definition201_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_linker_libs_definition207  */
static	ANTLR3_BITWORD FOLLOW_20_in_linker_libs_definition207_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_linker_libs_definition207	= { FOLLOW_20_in_linker_libs_definition207_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_typemap228  */
static	ANTLR3_BITWORD FOLLOW_21_in_typemap228_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000C00000) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_typemap228	= { FOLLOW_21_in_typemap228_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_typemap231  */
static	ANTLR3_BITWORD FOLLOW_22_in_typemap231_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_typemap231	= { FOLLOW_22_in_typemap231_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_typemap234  */
static	ANTLR3_BITWORD FOLLOW_23_in_typemap234_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_typemap234	= { FOLLOW_23_in_typemap234_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_typemap242  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_typemap242_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001080010) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_typemap242	= { FOLLOW_IDENTIFIER_in_typemap242_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_typemap249  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_typemap249_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001080010) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_typemap249	= { FOLLOW_IDENTIFIER_in_typemap249_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_typemap256  */
static	ANTLR3_BITWORD FOLLOW_24_in_typemap256_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001080000) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_typemap256	= { FOLLOW_24_in_typemap256_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_typemap264  */
static	ANTLR3_BITWORD FOLLOW_19_in_typemap264_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_typemap264	= { FOLLOW_19_in_typemap264_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_typemap270  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_typemap270_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001100010) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_typemap270	= { FOLLOW_IDENTIFIER_in_typemap270_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_typemap277  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_typemap277_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001100010) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_typemap277	= { FOLLOW_IDENTIFIER_in_typemap277_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_typemap284  */
static	ANTLR3_BITWORD FOLLOW_24_in_typemap284_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001100000) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_typemap284	= { FOLLOW_24_in_typemap284_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_typemap290  */
static	ANTLR3_BITWORD FOLLOW_20_in_typemap290_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_typemap290	= { FOLLOW_20_in_typemap290_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_definition_in_interface_definition310  */
static	ANTLR3_BITWORD FOLLOW_function_definition_in_interface_definition310_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_function_definition_in_interface_definition310	= { FOLLOW_function_definition_in_interface_definition310_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_type_in_function_definition331  */
static	ANTLR3_BITWORD FOLLOW_type_in_function_definition331_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_type_in_function_definition331	= { FOLLOW_type_in_function_definition331_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_function_definition333  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_function_definition333_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002000000) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_function_definition333	= { FOLLOW_IDENTIFIER_in_function_definition333_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_25_in_function_definition335  */
static	ANTLR3_BITWORD FOLLOW_25_in_function_definition335_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000010) };
static  ANTLR3_BITSET_LIST FOLLOW_25_in_function_definition335	= { FOLLOW_25_in_function_definition335_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_parameters_list_in_function_definition338  */
static	ANTLR3_BITWORD FOLLOW_parameters_list_in_function_definition338_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_parameters_list_in_function_definition338	= { FOLLOW_parameters_list_in_function_definition338_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_26_in_function_definition343  */
static	ANTLR3_BITWORD FOLLOW_26_in_function_definition343_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_26_in_function_definition343	= { FOLLOW_26_in_function_definition343_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_function_definition345  */
static	ANTLR3_BITWORD FOLLOW_20_in_function_definition345_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_function_definition345	= { FOLLOW_20_in_function_definition345_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_param_definition_in_parameters_list369  */
static	ANTLR3_BITWORD FOLLOW_param_definition_in_parameters_list369_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000002) };
static  ANTLR3_BITSET_LIST FOLLOW_param_definition_in_parameters_list369	= { FOLLOW_param_definition_in_parameters_list369_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_27_in_parameters_list375  */
static	ANTLR3_BITWORD FOLLOW_27_in_parameters_list375_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_27_in_parameters_list375	= { FOLLOW_27_in_parameters_list375_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_param_definition_in_parameters_list379  */
static	ANTLR3_BITWORD FOLLOW_param_definition_in_parameters_list379_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000002) };
static  ANTLR3_BITSET_LIST FOLLOW_param_definition_in_parameters_list379	= { FOLLOW_param_definition_in_parameters_list379_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_param_definition406  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_param_definition406_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000012) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_param_definition406	= { FOLLOW_IDENTIFIER_in_param_definition406_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_param_definition413  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_param_definition413_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000012) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_param_definition413	= { FOLLOW_IDENTIFIER_in_param_definition413_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_param_definition419  */
static	ANTLR3_BITWORD FOLLOW_24_in_param_definition419_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000012) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_param_definition419	= { FOLLOW_24_in_param_definition419_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_type457  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_type457_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000012) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_type457	= { FOLLOW_IDENTIFIER_in_type457_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_type464  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_type464_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000012) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_type464	= { FOLLOW_IDENTIFIER_in_type464_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_type472  */
static	ANTLR3_BITWORD FOLLOW_24_in_type472_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000002) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_type472	= { FOLLOW_24_in_type472_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start compilation_unit
 * ubibind.g:57:4: compilation_unit[SParamOptions options] : module_declaration raw_definition ( linker_libs_definition )? ( typemap )* ( interface_definition )* EOF ;
 */
static void
compilation_unit(pubibindParser ctx, SParamOptions options)
{   
    ANTLR3_UINT32 compilation_unit_StartIndex;
    /* Initialize rule variables
     */
    compilation_unit_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(1)) )
    {
        return ; 
    }
    {
        // ubibind.g:57:45: ( module_declaration raw_definition ( linker_libs_definition )? ( typemap )* ( interface_definition )* EOF )
        // ubibind.g:59:2: module_declaration raw_definition ( linker_libs_definition )? ( typemap )* ( interface_definition )* EOF
        {
            FOLLOWPUSH(FOLLOW_module_declaration_in_compilation_unit112);
            module_declaration(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulecompilation_unitEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            FOLLOWPUSH(FOLLOW_raw_definition_in_compilation_unit115);
            raw_definition(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulecompilation_unitEx;
            }
            if (HASFAILED())
            {
                return ;
            }

            // ubibind.g:61:2: ( linker_libs_definition )?
            {
                int alt1=2;
                {
                    int LA1_0 = LA(1);
                    if ( (LA1_0 == 18) ) 
                    {
                        alt1=1;
                    }
                }
                switch (alt1) 
                {
            	case 1:
            	    // ubibind.g:61:3: linker_libs_definition
            	    {
            	        FOLLOWPUSH(FOLLOW_linker_libs_definition_in_compilation_unit119);
            	        linker_libs_definition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulecompilation_unitEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }

            	    }
            	    break;

                }
            }
            if ( BACKTRACKING==0 ) 
            {
                 bindSource.writeHeaders(); 
            }

            // ubibind.g:63:2: ( typemap )*

            for (;;)
            {
                int alt2=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA2_0 = LA(1);
                    if ( (LA2_0 == 21) ) 
                    {
                        alt2=1;
                    }

                }
                switch (alt2) 
                {
            	case 1:
            	    // ubibind.g:63:3: typemap
            	    {
            	        FOLLOWPUSH(FOLLOW_typemap_in_compilation_unit128);
            	        typemap(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulecompilation_unitEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


            // ubibind.g:64:2: ( interface_definition )*

            for (;;)
            {
                int alt3=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA3_0 = LA(1);
                    if ( (LA3_0 == IDENTIFIER) ) 
                    {
                        alt3=1;
                    }

                }
                switch (alt3) 
                {
            	case 1:
            	    // ubibind.g:64:3: interface_definition
            	    {
            	        FOLLOWPUSH(FOLLOW_interface_definition_in_compilation_unit134);
            	        interface_definition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulecompilation_unitEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }

            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */

             MATCHT(EOF, &FOLLOW_EOF_in_compilation_unit139); 
            if  (HASEXCEPTION())
            {
                goto rulecompilation_unitEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {

                		bindSource.writeFooters();
                		std::ofstream out(options.outputFilename.c_str(), std::ios_base::out);
                		out << bindSource.getCppText();
                		std::ofstream out2("Makefile", std::ios_base::out);
                		out2 << bindSource.getMakefileText();
                	
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulecompilation_unitEx; /* Prevent compiler warnings */
    rulecompilation_unitEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(1, compilation_unit_StartIndex); }
    return ;
}
/* $ANTLR end compilation_unit */

/** 
 * $ANTLR start module_declaration
 * ubibind.g:76:4: module_declaration : '%module' IDENTIFIER ;
 */
static void
module_declaration(pubibindParser ctx)
{   
    ANTLR3_UINT32 module_declaration_StartIndex;
    pANTLR3_COMMON_TOKEN    IDENTIFIER1;

    /* Initialize rule variables
     */
    module_declaration_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(2)) )
    {
        return ; 
    }
    IDENTIFIER1       = NULL;

    {
        // ubibind.g:76:23: ( '%module' IDENTIFIER )
        // ubibind.g:78:2: '%module' IDENTIFIER
        {
             MATCHT(17, &FOLLOW_17_in_module_declaration158); 
            if  (HASEXCEPTION())
            {
                goto rulemodule_declarationEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            IDENTIFIER1 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_module_declaration160); 
            if  (HASEXCEPTION())
            {
                goto rulemodule_declarationEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {
                 bindSource.setModuleName(GETTEXT(IDENTIFIER1)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulemodule_declarationEx; /* Prevent compiler warnings */
    rulemodule_declarationEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(2, module_declaration_StartIndex); }
    return ;
}
/* $ANTLR end module_declaration */

/** 
 * $ANTLR start raw_definition
 * ubibind.g:82:4: raw_definition : RAW_DEFINITION ;
 */
static void
raw_definition(pubibindParser ctx)
{   
    ANTLR3_UINT32 raw_definition_StartIndex;
    pANTLR3_COMMON_TOKEN    RAW_DEFINITION2;

    /* Initialize rule variables
     */
    raw_definition_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(3)) )
    {
        return ; 
    }
    RAW_DEFINITION2       = NULL;

    {
        // ubibind.g:82:19: ( RAW_DEFINITION )
        // ubibind.g:84:2: RAW_DEFINITION
        {
            RAW_DEFINITION2 = (pANTLR3_COMMON_TOKEN) MATCHT(RAW_DEFINITION, &FOLLOW_RAW_DEFINITION_in_raw_definition178); 
            if  (HASEXCEPTION())
            {
                goto ruleraw_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {
                 bindSource.setDefinitions(GETTEXT(RAW_DEFINITION2)); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleraw_definitionEx; /* Prevent compiler warnings */
    ruleraw_definitionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(3, raw_definition_StartIndex); }
    return ;
}
/* $ANTLR end raw_definition */

/** 
 * $ANTLR start linker_libs_definition
 * ubibind.g:88:4: linker_libs_definition : '%linkerlibs' '=' ( IDENTIFIER )+ ';' ;
 */
static void
linker_libs_definition(pubibindParser ctx)
{   
    ANTLR3_UINT32 linker_libs_definition_StartIndex;
    pANTLR3_COMMON_TOKEN    IDENTIFIER3;

    /* Initialize rule variables
     */
    linker_libs_definition_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(4)) )
    {
        return ; 
    }
    IDENTIFIER3       = NULL;

    {
        // ubibind.g:90:2: ( '%linkerlibs' '=' ( IDENTIFIER )+ ';' )
        // ubibind.g:90:4: '%linkerlibs' '=' ( IDENTIFIER )+ ';'
        {
             MATCHT(18, &FOLLOW_18_in_linker_libs_definition196); 
            if  (HASEXCEPTION())
            {
                goto rulelinker_libs_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }
             MATCHT(19, &FOLLOW_19_in_linker_libs_definition198); 
            if  (HASEXCEPTION())
            {
                goto rulelinker_libs_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            // ubibind.g:90:22: ( IDENTIFIER )+
            {
                int cnt4=0;

                for (;;)
                {
                    int alt4=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA4_0 = LA(1);
            	    if ( (LA4_0 == IDENTIFIER) ) 
            	    {
            	        alt4=1;
            	    }

            	}
            	switch (alt4) 
            	{
            	    case 1:
            	        // ubibind.g:90:23: IDENTIFIER
            	        {
            	            IDENTIFIER3 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_linker_libs_definition201); 
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulelinker_libs_definitionEx;
            	            }
            	            if (HASFAILED())
            	            {
            	                return ;
            	            }
            	            if ( BACKTRACKING==0 ) 
            	            {
            	                bindSource.addLinkerLib(GETTEXT(IDENTIFIER3));
            	            }

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt4 >= 1 )
            		{
            		    goto loop4;
            		}
            		if (BACKTRACKING>0)
            		{
            		    FAILEDFLAG = ANTLR3_TRUE; 
            		    return ;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto rulelinker_libs_definitionEx;
            	}
            	cnt4++;
                }
                loop4: ;	/* Jump to here if this rule does not match */
            }
             MATCHT(20, &FOLLOW_20_in_linker_libs_definition207); 
            if  (HASEXCEPTION())
            {
                goto rulelinker_libs_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulelinker_libs_definitionEx; /* Prevent compiler warnings */
    rulelinker_libs_definitionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(4, linker_libs_definition_StartIndex); }
    return ;
}
/* $ANTLR end linker_libs_definition */

/** 
 * $ANTLR start typemap
 * ubibind.g:94:4: typemap : '%typemap' ( 'in' | 'out' ) type1From= IDENTIFIER (type2From= IDENTIFIER )* ( '*' )* '=' type1To= IDENTIFIER (type2To= IDENTIFIER )* ( '*' )* ';' ;
 */
static void
typemap(pubibindParser ctx)
{   
    ANTLR3_UINT32 typemap_StartIndex;

    	std::string typeFrom;
    	std::string typeTo;
    	int typemapType;

    pANTLR3_COMMON_TOKEN    type1From;
    pANTLR3_COMMON_TOKEN    type2From;
    pANTLR3_COMMON_TOKEN    type1To;
    pANTLR3_COMMON_TOKEN    type2To;

    /* Initialize rule variables
     */
    typemap_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(5)) )
    {
        return ; 
    }
    type1From       = NULL;
    type2From       = NULL;
    type1To       = NULL;
    type2To       = NULL;

    {
        // ubibind.g:101:2: ( '%typemap' ( 'in' | 'out' ) type1From= IDENTIFIER (type2From= IDENTIFIER )* ( '*' )* '=' type1To= IDENTIFIER (type2To= IDENTIFIER )* ( '*' )* ';' )
        // ubibind.g:101:4: '%typemap' ( 'in' | 'out' ) type1From= IDENTIFIER (type2From= IDENTIFIER )* ( '*' )* '=' type1To= IDENTIFIER (type2To= IDENTIFIER )* ( '*' )* ';'
        {
             MATCHT(21, &FOLLOW_21_in_typemap228); 
            if  (HASEXCEPTION())
            {
                goto ruletypemapEx;
            }
            if (HASFAILED())
            {
                return ;
            }

            // ubibind.g:101:15: ( 'in' | 'out' )
            {
                int alt5=2;

                {
                    int LA5_0 = LA(1);
                    if ( (LA5_0 == 22) ) 
                    {
                        alt5=1;
                    }
                    else if ( (LA5_0 == 23) ) 
                    {
                        alt5=2;
                    }
                    else 
                    {
                        if (BACKTRACKING>0)
                        {
                            FAILEDFLAG = ANTLR3_TRUE; 
                            return ;
                        }
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 5;
                        EXCEPTION->state        = 0;


                        goto ruletypemapEx;
                    }
                }
                switch (alt5) 
                {
            	case 1:
            	    // ubibind.g:101:16: 'in'
            	    {
            	         MATCHT(22, &FOLLOW_22_in_typemap231); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypemapEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            typemapType=1;
            	        }

            	    }
            	    break;
            	case 2:
            	    // ubibind.g:101:37: 'out'
            	    {
            	         MATCHT(23, &FOLLOW_23_in_typemap234); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypemapEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            typemapType=2;
            	        }

            	    }
            	    break;

                }
            }
            type1From = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_typemap242); 
            if  (HASEXCEPTION())
            {
                goto ruletypemapEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {
                typeFrom=GETTEXT(type1From);
            }

            // ubibind.g:102:56: (type2From= IDENTIFIER )*

            for (;;)
            {
                int alt6=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA6_0 = LA(1);
                    if ( (LA6_0 == IDENTIFIER) ) 
                    {
                        alt6=1;
                    }

                }
                switch (alt6) 
                {
            	case 1:
            	    // ubibind.g:102:57: type2From= IDENTIFIER
            	    {
            	        type2From = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_typemap249); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypemapEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            typeFrom += " " + GETTEXT(type2From);
            	        }

            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


            // ubibind.g:102:121: ( '*' )*

            for (;;)
            {
                int alt7=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA7_0 = LA(1);
                    if ( (LA7_0 == 24) ) 
                    {
                        alt7=1;
                    }

                }
                switch (alt7) 
                {
            	case 1:
            	    // ubibind.g:102:122: '*'
            	    {
            	         MATCHT(24, &FOLLOW_24_in_typemap256); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypemapEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            typeFrom += "*"; 
            	        }

            	    }
            	    break;

            	default:
            	    goto loop7;	/* break out of the loop */
            	    break;
                }
            }
            loop7: ; /* Jump out to here if this rule does not match */

             MATCHT(19, &FOLLOW_19_in_typemap264); 
            if  (HASEXCEPTION())
            {
                goto ruletypemapEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            type1To = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_typemap270); 
            if  (HASEXCEPTION())
            {
                goto ruletypemapEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {
                typeTo=GETTEXT(type1To);
            }

            // ubibind.g:104:50: (type2To= IDENTIFIER )*

            for (;;)
            {
                int alt8=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA8_0 = LA(1);
                    if ( (LA8_0 == IDENTIFIER) ) 
                    {
                        alt8=1;
                    }

                }
                switch (alt8) 
                {
            	case 1:
            	    // ubibind.g:104:51: type2To= IDENTIFIER
            	    {
            	        type2To = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_typemap277); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypemapEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            typeTo += " " + GETTEXT(type2To);
            	        }

            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */


            // ubibind.g:104:109: ( '*' )*

            for (;;)
            {
                int alt9=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA9_0 = LA(1);
                    if ( (LA9_0 == 24) ) 
                    {
                        alt9=1;
                    }

                }
                switch (alt9) 
                {
            	case 1:
            	    // ubibind.g:104:110: '*'
            	    {
            	         MATCHT(24, &FOLLOW_24_in_typemap284); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypemapEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            typeTo += "*"; 
            	        }

            	    }
            	    break;

            	default:
            	    goto loop9;	/* break out of the loop */
            	    break;
                }
            }
            loop9: ; /* Jump out to here if this rule does not match */

             MATCHT(20, &FOLLOW_20_in_typemap290); 
            if  (HASEXCEPTION())
            {
                goto ruletypemapEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {
                if (typemapType == 1) bindSource.addTypeMapIn(typeFrom, typeTo); else bindSource.addTypeMapOut(typeFrom, typeTo);
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruletypemapEx; /* Prevent compiler warnings */
    ruletypemapEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(5, typemap_StartIndex); }
    return ;
}
/* $ANTLR end typemap */

/** 
 * $ANTLR start interface_definition
 * ubibind.g:109:4: interface_definition : function_definition ;
 */
static void
interface_definition(pubibindParser ctx)
{   
    ANTLR3_UINT32 interface_definition_StartIndex;
    /* Initialize rule variables
     */
    interface_definition_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(6)) )
    {
        return ; 
    }
    {
        // ubibind.g:109:25: ( function_definition )
        // ubibind.g:111:2: function_definition
        {
            FOLLOWPUSH(FOLLOW_function_definition_in_interface_definition310);
            function_definition(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleinterface_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleinterface_definitionEx; /* Prevent compiler warnings */
    ruleinterface_definitionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(6, interface_definition_StartIndex); }
    return ;
}
/* $ANTLR end interface_definition */

/** 
 * $ANTLR start function_definition
 * ubibind.g:115:4: function_definition : type IDENTIFIER '(' ( parameters_list[parameters] )? ')' ';' ;
 */
static void
function_definition(pubibindParser ctx)
{   
    ANTLR3_UINT32 function_definition_StartIndex;

    	std::vector<std::string> parameters;

    pANTLR3_COMMON_TOKEN    IDENTIFIER5;
    ubibindParser_type_return type4;
    #undef	RETURN_TYPE_type4
    #define	RETURN_TYPE_type4 ubibindParser_type_return

    /* Initialize rule variables
     */
    function_definition_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(7)) )
    {
        return ; 
    }
    IDENTIFIER5       = NULL;

    {
        // ubibind.g:121:2: ( type IDENTIFIER '(' ( parameters_list[parameters] )? ')' ';' )
        // ubibind.g:121:4: type IDENTIFIER '(' ( parameters_list[parameters] )? ')' ';'
        {
            FOLLOWPUSH(FOLLOW_type_in_function_definition331);
            type4=type(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunction_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            IDENTIFIER5 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_function_definition333); 
            if  (HASEXCEPTION())
            {
                goto rulefunction_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }
             MATCHT(25, &FOLLOW_25_in_function_definition335); 
            if  (HASEXCEPTION())
            {
                goto rulefunction_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }

            // ubibind.g:121:24: ( parameters_list[parameters] )?
            {
                int alt10=2;
                {
                    int LA10_0 = LA(1);
                    if ( (LA10_0 == IDENTIFIER) ) 
                    {
                        alt10=1;
                    }
                }
                switch (alt10) 
                {
            	case 1:
            	    // ubibind.g:121:25: parameters_list[parameters]
            	    {
            	        FOLLOWPUSH(FOLLOW_parameters_list_in_function_definition338);
            	        parameters_list(ctx, parameters);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunction_definitionEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }

            	    }
            	    break;

                }
            }
             MATCHT(26, &FOLLOW_26_in_function_definition343); 
            if  (HASEXCEPTION())
            {
                goto rulefunction_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }
             MATCHT(20, &FOLLOW_20_in_function_definition345); 
            if  (HASEXCEPTION())
            {
                goto rulefunction_definitionEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {
                 bindSource.addFunction(type4.sret, GETTEXT(IDENTIFIER5), parameters); 
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulefunction_definitionEx; /* Prevent compiler warnings */
    rulefunction_definitionEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(7, function_definition_StartIndex); }
    return ;
}
/* $ANTLR end function_definition */

/** 
 * $ANTLR start parameters_list
 * ubibind.g:126:4: parameters_list[std::vector<std::string> &parameters] : param1= param_definition ( ',' param2= param_definition )* ;
 */
static void
parameters_list(pubibindParser ctx, std::vector<std::string> &parameters)
{   
    ANTLR3_UINT32 parameters_list_StartIndex;
    ubibindParser_param_definition_return param1;
    #undef	RETURN_TYPE_param1
    #define	RETURN_TYPE_param1 ubibindParser_param_definition_return

    ubibindParser_param_definition_return param2;
    #undef	RETURN_TYPE_param2
    #define	RETURN_TYPE_param2 ubibindParser_param_definition_return

    /* Initialize rule variables
     */
    parameters_list_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(8)) )
    {
        return ; 
    }



    {
        // ubibind.g:128:2: (param1= param_definition ( ',' param2= param_definition )* )
        // ubibind.g:128:4: param1= param_definition ( ',' param2= param_definition )*
        {
            FOLLOWPUSH(FOLLOW_param_definition_in_parameters_list369);
            param1=param_definition(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleparameters_listEx;
            }
            if (HASFAILED())
            {
                return ;
            }
            if ( BACKTRACKING==0 ) 
            {
                parameters.push_back(param1.ret);
            }

            // ubibind.g:128:65: ( ',' param2= param_definition )*

            for (;;)
            {
                int alt11=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA11_0 = LA(1);
                    if ( (LA11_0 == 27) ) 
                    {
                        alt11=1;
                    }

                }
                switch (alt11) 
                {
            	case 1:
            	    // ubibind.g:128:67: ',' param2= param_definition
            	    {
            	         MATCHT(27, &FOLLOW_27_in_parameters_list375); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleparameters_listEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        FOLLOWPUSH(FOLLOW_param_definition_in_parameters_list379);
            	        param2=param_definition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleparameters_listEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return ;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            parameters.push_back(param2.ret);
            	        }

            	    }
            	    break;

            	default:
            	    goto loop11;	/* break out of the loop */
            	    break;
                }
            }
            loop11: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleparameters_listEx; /* Prevent compiler warnings */
    ruleparameters_listEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(8, parameters_list_StartIndex); }
    return ;
}
/* $ANTLR end parameters_list */

/** 
 * $ANTLR start param_definition
 * ubibind.g:132:4: param_definition returns [int bogus, std::string ret] : id1= IDENTIFIER (id2= IDENTIFIER | '*' )* ;
 */
static ubibindParser_param_definition_return
param_definition(pubibindParser ctx)
{   
    ubibindParser_param_definition_return retval;
    ANTLR3_UINT32 param_definition_StartIndex;
    pANTLR3_COMMON_TOKEN    id1;
    pANTLR3_COMMON_TOKEN    id2;

    /* Initialize rule variables
     */
    param_definition_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(9)) )
    {
    	retval.start = 0;

        return retval; 
    }
    id1       = NULL;
    id2       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    {
        // ubibind.g:134:2: (id1= IDENTIFIER (id2= IDENTIFIER | '*' )* )
        // ubibind.g:134:4: id1= IDENTIFIER (id2= IDENTIFIER | '*' )*
        {
            id1 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_param_definition406); 
            if  (HASEXCEPTION())
            {
                goto ruleparam_definitionEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
            if ( BACKTRACKING==0 ) 
            {
                retval.ret += GETTEXT(id1);
            }

            // ubibind.g:134:44: (id2= IDENTIFIER | '*' )*

            for (;;)
            {
                int alt12=3;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA12_0 = LA(1);
                    if ( (LA12_0 == IDENTIFIER) ) 
                    {
                        alt12=1;
                    }
                    else if ( (LA12_0 == 24) ) 
                    {
                        alt12=2;
                    }

                }
                switch (alt12) 
                {
            	case 1:
            	    // ubibind.g:134:45: id2= IDENTIFIER
            	    {
            	        id2 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_param_definition413); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleparam_definitionEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            retval.ret += " " + GETTEXT(id2);
            	        }

            	    }
            	    break;
            	case 2:
            	    // ubibind.g:134:93: '*'
            	    {
            	         MATCHT(24, &FOLLOW_24_in_param_definition419); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleparam_definitionEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	            retval.ret += '*';
            	        }

            	    }
            	    break;

            	default:
            	    goto loop12;	/* break out of the loop */
            	    break;
                }
            }
            loop12: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleparam_definitionEx; /* Prevent compiler warnings */
    ruleparam_definitionEx: ;
    retval.stop = LT(-1);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(9, param_definition_StartIndex); }
    return retval;
}
/* $ANTLR end param_definition */

/** 
 * $ANTLR start type
 * ubibind.g:149:4: type returns [LiteralType iret, std::string sret] : id1= IDENTIFIER (id2= IDENTIFIER )* ( '*' )* ;
 */
static ubibindParser_type_return
type(pubibindParser ctx)
{   
    ubibindParser_type_return retval;
    ANTLR3_UINT32 type_StartIndex;
    pANTLR3_COMMON_TOKEN    id1;
    pANTLR3_COMMON_TOKEN    id2;

    /* Initialize rule variables
     */
    type_StartIndex = INDEX();


    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(10)) )
    {
    	retval.start = 0;

        return retval; 
    }
    id1       = NULL;
    id2       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    {
        // ubibind.g:149:54: (id1= IDENTIFIER (id2= IDENTIFIER )* ( '*' )* )
        // ubibind.g:151:2: id1= IDENTIFIER (id2= IDENTIFIER )* ( '*' )*
        {
            id1 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_type457); 
            if  (HASEXCEPTION())
            {
                goto ruletypeEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
            if ( BACKTRACKING==0 ) 
            {
                 retval.sret= GETTEXT(id1); 
            }

            // ubibind.g:151:44: (id2= IDENTIFIER )*

            for (;;)
            {
                int alt13=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA13_0 = LA(1);
                    if ( (LA13_0 == IDENTIFIER) ) 
                    {
                        {
                           /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                            */
                            int LA13_2 = LA(2);
                            if ( (LA13_2 == IDENTIFIER || LA13_2 == 24) ) 
                            {
                                alt13=1;
                            }

                        }
                    }

                }
                switch (alt13) 
                {
            	case 1:
            	    // ubibind.g:151:45: id2= IDENTIFIER
            	    {
            	        id2 = (pANTLR3_COMMON_TOKEN) MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_type464); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypeEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	             retval.sret += " " + GETTEXT(id2); 
            	        }

            	    }
            	    break;

            	default:
            	    goto loop13;	/* break out of the loop */
            	    break;
                }
            }
            loop13: ; /* Jump out to here if this rule does not match */


            // ubibind.g:151:97: ( '*' )*

            for (;;)
            {
                int alt14=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA14_0 = LA(1);
                    if ( (LA14_0 == 24) ) 
                    {
                        alt14=1;
                    }

                }
                switch (alt14) 
                {
            	case 1:
            	    // ubibind.g:151:98: '*'
            	    {
            	         MATCHT(24, &FOLLOW_24_in_type472); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruletypeEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }
            	        if ( BACKTRACKING==0 ) 
            	        {
            	             retval.sret += '*'; 
            	        }

            	    }
            	    break;

            	default:
            	    goto loop14;	/* break out of the loop */
            	    break;
                }
            }
            loop14: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruletypeEx; /* Prevent compiler warnings */
    ruletypeEx: ;
    retval.stop = LT(-1);

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    if ( BACKTRACKING>0 ) { MEMOIZE(10, type_StartIndex); }
    return retval;
}
/* $ANTLR end type */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
