/** \file
 *  This C source file was generated by $ANTLR version 3.1.3 Mar 18, 2009 10:09:25
 *
 *     -  From the grammar source file : ubibind.g
 *     -                            On : 2013-03-29 20:01:58
 *     -                 for the lexer : ubibindLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

	#define	ANTLR3_INLINE_INPUT_ASCII

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ubibindLexer.h"
/* ----------------------------------------- */


/** String literals used by ubibindLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x25, 0x6D, 0x6F, 0x64, 0x75, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x25, 0x6C, 0x69, 0x6E, 0x6B, 0x65, 0x72, 0x6C, 0x69, 0x62, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x25, 0x74, 0x79, 0x70, 0x65, 0x6D, 0x61, 0x70,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x69, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x6F, 0x75, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x74, 0x72, 0x75, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x66, 0x61, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x25, 0x7B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x25, 0x7D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x2F, 0x2A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x2A, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pubibindLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pubibindLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pubibindLexer_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__17    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__18    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__19    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__20    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__21    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__22    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__23    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__24    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__25    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__26    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mT__27    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mINTEGER_LITERAL    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mREAL_LITERAL    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mCHARACTER_LITERAL    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mSTRING_LITERAL    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mBOOLEAN_LITERAL    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mESCAPE_SEQUENCE    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mIDENTIFIER    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mRAW_DEFINITION    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mLETTER    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mDIGIT    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mWS    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mCOMMENT    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mLINE_COMMENT    (pubibindLexer ctx);
static ANTLR3_INLINE  void	mTokens    (pubibindLexer ctx);
static void	ubibindLexerFree(pubibindLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



	static ANTLR3_BOOLEAN enumIsKeyword = ANTLR3_TRUE;


static void
ubibindLexerFree  (pubibindLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ubibind.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called ubibindLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success pubibindLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pubibindLexer ubibindLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return ubibindLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called ubibindLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success pubibindLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pubibindLexer ubibindLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pubibindLexer ctx; // Context structure we will build and return

    ctx = (pubibindLexer) ANTLR3_CALLOC(1, sizeof(ubibindLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in ubibindLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our ubibindLexer interface
     */
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mINTEGER_LITERAL	= mINTEGER_LITERAL;
    ctx->mREAL_LITERAL	= mREAL_LITERAL;
    ctx->mCHARACTER_LITERAL	= mCHARACTER_LITERAL;
    ctx->mSTRING_LITERAL	= mSTRING_LITERAL;
    ctx->mBOOLEAN_LITERAL	= mBOOLEAN_LITERAL;
    ctx->mESCAPE_SEQUENCE	= mESCAPE_SEQUENCE;
    ctx->mIDENTIFIER	= mIDENTIFIER;
    ctx->mRAW_DEFINITION	= mRAW_DEFINITION;
    ctx->mLETTER	= mLETTER;
    ctx->mDIGIT	= mDIGIT;
    ctx->mWS	= mWS;
    ctx->mCOMMENT	= mCOMMENT;
    ctx->mLINE_COMMENT	= mLINE_COMMENT;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= ubibindLexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | INTEGER_LITERAL | REAL_LITERAL | CHARACTER_LITERAL | STRING_LITERAL | BOOLEAN_LITERAL | IDENTIFIER | RAW_DEFINITION | WS | COMMENT | LINE_COMMENT );
 */
static const ANTLR3_INT32 dfa14_eot[39] =
    {
	-1, -1, -1, -1, 16, 16, -1, -1, -1, -1, 25, -1, -1, -1, 16, 16, -1, -1, 
	-1, -1, -1, -1, -1, 30, 16, -1, 16, 16, -1, -1, -1, 34, 16, 16, -1, 37, 
	16, -1, 37
    };
static const ANTLR3_INT32 dfa14_eof[39] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1
    };
static const ANTLR3_INT32 dfa14_min[39] =
    {
	9, 108, -1, -1, 110, 117, -1, -1, -1, -1, 46, -1, -1, -1, 114, 97, -1, 
	-1, 42, -1, -1, -1, -1, 48, 116, -1, 117, 108, -1, -1, -1, 48, 101, 115, 
	-1, 48, 101, -1, 48
    };
static const ANTLR3_INT32 dfa14_max[39] =
    {
	122, 123, -1, -1, 110, 117, -1, -1, -1, -1, 57, -1, -1, -1, 114, 97, -1, 
	-1, 47, -1, -1, -1, -1, 122, 116, -1, 117, 108, -1, -1, -1, 122, 101, 115, 
	-1, 122, 101, -1, 122
    };
static const ANTLR3_INT32 dfa14_accept[39] =
    {
	-1, -1, 3, 4, -1, -1, 8, 9, 10, 11, -1, 13, 14, 15, -1, -1, 17, 19, -1, 
	1, 2, 5, 18, -1, -1, 12, -1, -1, 20, 21, 6, -1, -1, -1, 7, -1, -1, 16, 
	-1
    };
static const ANTLR3_INT32 dfa14_special[39] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa14_T_empty	    NULL

static const ANTLR3_INT32 dfa14_T0[] =
    {
	36
    };static const ANTLR3_INT32 dfa14_T1[] =
    {
	33
    };static const ANTLR3_INT32 dfa14_T2[] =
    {
	24
    };static const ANTLR3_INT32 dfa14_T3[] =
    {
	38
    };static const ANTLR3_INT32 dfa14_T4[] =
    {
	20, 19, -1, -1, -1, -1, -1, -1, 21, -1, -1, -1, -1, -1, -1, 22
    };static const ANTLR3_INT32 dfa14_T5[] =
    {
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16, -1, -1, -1, -1, -1, -1, -1, 16, 
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 
	16, 16, 16, 16, 16, 16, 16, -1, -1, -1, -1, 16, -1, 16, 16, 16, 16, 16, 
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 
	16, 16, 16
    };static const ANTLR3_INT32 dfa14_T6[] =
    {
	11, -1, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10
    };static const ANTLR3_INT32 dfa14_T7[] =
    {
	26
    };static const ANTLR3_INT32 dfa14_T8[] =
    {
	27
    };static const ANTLR3_INT32 dfa14_T9[] =
    {
	31
    };static const ANTLR3_INT32 dfa14_T10[] =
    {
	28, -1, -1, -1, -1, 29
    };static const ANTLR3_INT32 dfa14_T11[] =
    {
	17, 17, -1, 17, 17, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 17, -1, 13, -1, -1, 1, -1, 12, 7, 8, 6, -1, 9, -1, 
	11, 18, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, -1, 3, -1, 2, -1, -1, -1, 
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 
	16, 16, 16, 16, 16, 16, 16, 16, -1, -1, -1, -1, -1, -1, 16, 16, 16, 16, 
	16, 15, 16, 16, 4, 16, 16, 16, 16, 16, 5, 16, 16, 16, 16, 14, 16, 16, 16, 
	16, 16, 16
    };static const ANTLR3_INT32 dfa14_T12[] =
    {
	32
    };static const ANTLR3_INT32 dfa14_T13[] =
    {
	35
    };static const ANTLR3_INT32 dfa14_T14[] =
    {
	23
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa14_transitions[] =
{
    dfa14_T11, dfa14_T4, dfa14_T_empty, dfa14_T_empty, dfa14_T14, dfa14_T2, 
    dfa14_T_empty, dfa14_T_empty, dfa14_T_empty, dfa14_T_empty, dfa14_T6, 
    dfa14_T_empty, dfa14_T_empty, dfa14_T_empty, dfa14_T7, dfa14_T8, dfa14_T_empty, 
    dfa14_T_empty, dfa14_T10, dfa14_T_empty, dfa14_T_empty, dfa14_T_empty, 
    dfa14_T_empty, dfa14_T5, dfa14_T9, dfa14_T_empty, dfa14_T12, dfa14_T1, 
    dfa14_T_empty, dfa14_T_empty, dfa14_T_empty, dfa14_T5, dfa14_T13, dfa14_T0, 
    dfa14_T_empty, dfa14_T5, dfa14_T3, dfa14_T_empty, dfa14_T5	
};


/* Declare tracking structure for Cyclic DFA 14
 */
static
ANTLR3_CYCLIC_DFA cdfa14
    =	{
	    14,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | INTEGER_LITERAL | REAL_LITERAL | CHARACTER_LITERAL | STRING_LITERAL | BOOLEAN_LITERAL | IDENTIFIER | RAW_DEFINITION | WS | COMMENT | LINE_COMMENT );",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa14_eot,	    /* EOT table			    */
	    dfa14_eof,	    /* EOF table			    */
	    dfa14_min,	    /* Minimum tokens for each state    */
	    dfa14_max,	    /* Maximum tokens for each state    */
	    dfa14_accept,	/* Accept table			    */
	    dfa14_special,	/* Special transition states	    */
	    dfa14_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 14
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 17:7: ( '%module' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;
       
    
    // ubibind.g:17:7: ( '%module' )
    // ubibind.g:17:9: '%module'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 18:7: ( '%linkerlibs' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;
       
    
    // ubibind.g:18:7: ( '%linkerlibs' )
    // ubibind.g:18:9: '%linkerlibs'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 19:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;
       
    
    // ubibind.g:19:7: ( '=' )
    // ubibind.g:19:9: '='
    {
        MATCHC('='); 
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 20:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;
       
    
    // ubibind.g:20:7: ( ';' )
    // ubibind.g:20:9: ';'
    {
        MATCHC(';'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 21:7: ( '%typemap' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;
       
    
    // ubibind.g:21:7: ( '%typemap' )
    // ubibind.g:21:9: '%typemap'
    {
        MATCHS(lit_3); 
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 22:7: ( 'in' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;
       
    
    // ubibind.g:22:7: ( 'in' )
    // ubibind.g:22:9: 'in'
    {
        MATCHS(lit_4); 
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 23:7: ( 'out' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;
       
    
    // ubibind.g:23:7: ( 'out' )
    // ubibind.g:23:9: 'out'
    {
        MATCHS(lit_5); 
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 24:7: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;
       
    
    // ubibind.g:24:7: ( '*' )
    // ubibind.g:24:9: '*'
    {
        MATCHC('*'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 25:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;
       
    
    // ubibind.g:25:7: ( '(' )
    // ubibind.g:25:9: '('
    {
        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 26:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__26;
       
    
    // ubibind.g:26:7: ( ')' )
    // ubibind.g:26:9: ')'
    {
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 27:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;
       
    
    // ubibind.g:27:7: ( ',' )
    // ubibind.g:27:9: ','
    {
        MATCHC(','); 
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 258:17: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INTEGER_LITERAL
 *
 * Looks to match the characters the constitute the token INTEGER_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINTEGER_LITERAL(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INTEGER_LITERAL;
       
    
    // ubibind.g:258:17: ( ( '0' .. '9' )+ )
    // ubibind.g:258:19: ( '0' .. '9' )+
    {
        // ubibind.g:258:19: ( '0' .. '9' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA1_0 = LA(1);
        	    if ( (((LA1_0 >= '0') && (LA1_0 <= '9'))) ) 
        	    {
        	        alt1=1;
        	    }

        	}
        	switch (alt1) 
        	{
        	    case 1:
        	        // ubibind.g:258:20: '0' .. '9'
        	        {
        	            MATCHRANGE('0', '9'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleINTEGER_LITERALEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEGER_LITERALEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINTEGER_LITERALEx; /* Prevent compiler warnings */
    ruleINTEGER_LITERALEx: ;

}
// $ANTLR end INTEGER_LITERAL

//   Comes from: 261:4: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )+ | '.' ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start REAL_LITERAL
 *
 * Looks to match the characters the constitute the token REAL_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mREAL_LITERAL(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = REAL_LITERAL;
       
    
    {
        //  ubibind.g:261:4: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )+ | '.' ( '0' .. '9' )+ )
        
        ANTLR3_UINT32 alt5;

        alt5=2;


        {
            int LA5_0 = LA(1);
            if ( (((LA5_0 >= '0') && (LA5_0 <= '9'))) ) 
            {
                alt5=1;
            }
            else if ( (LA5_0 == '.') ) 
            {
                alt5=2;
            }
            else 
            {
            
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto ruleREAL_LITERALEx;
            }
        }
        switch (alt5) 
        {
    	case 1:
    	    // ubibind.g:261:7: ( '0' .. '9' )+ '.' ( '0' .. '9' )+
    	    {
    	        // ubibind.g:261:7: ( '0' .. '9' )+
    	        {
    	            int cnt2=0;

    	            for (;;)
    	            {
    	                int alt2=2;
    	        	{
    	        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	        	    */
    	        	    int LA2_0 = LA(1);
    	        	    if ( (((LA2_0 >= '0') && (LA2_0 <= '9'))) ) 
    	        	    {
    	        	        alt2=1;
    	        	    }

    	        	}
    	        	switch (alt2) 
    	        	{
    	        	    case 1:
    	        	        // ubibind.g:261:8: '0' .. '9'
    	        	        {
    	        	            MATCHRANGE('0', '9'); 
    	        	            if  (HASEXCEPTION())
    	        	            {
    	        	                goto ruleREAL_LITERALEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:
    	        	    
    	        		if ( cnt2 >= 1 )
    	        		{
    	        		    goto loop2;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleREAL_LITERALEx;
    	        	}
    	        	cnt2++;
    	            }
    	            loop2: ;	/* Jump to here if this rule does not match */
    	        }
    	        MATCHC('.'); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleREAL_LITERALEx;
    	        }

    	        // ubibind.g:261:23: ( '0' .. '9' )+
    	        {
    	            int cnt3=0;

    	            for (;;)
    	            {
    	                int alt3=2;
    	        	{
    	        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	        	    */
    	        	    int LA3_0 = LA(1);
    	        	    if ( (((LA3_0 >= '0') && (LA3_0 <= '9'))) ) 
    	        	    {
    	        	        alt3=1;
    	        	    }

    	        	}
    	        	switch (alt3) 
    	        	{
    	        	    case 1:
    	        	        // ubibind.g:261:24: '0' .. '9'
    	        	        {
    	        	            MATCHRANGE('0', '9'); 
    	        	            if  (HASEXCEPTION())
    	        	            {
    	        	                goto ruleREAL_LITERALEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:
    	        	    
    	        		if ( cnt3 >= 1 )
    	        		{
    	        		    goto loop3;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleREAL_LITERALEx;
    	        	}
    	        	cnt3++;
    	            }
    	            loop3: ;	/* Jump to here if this rule does not match */
    	        }

    	    }
    	    break;
    	case 2:
    	    // ubibind.g:262:7: '.' ( '0' .. '9' )+
    	    {
    	        MATCHC('.'); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleREAL_LITERALEx;
    	        }

    	        // ubibind.g:262:11: ( '0' .. '9' )+
    	        {
    	            int cnt4=0;

    	            for (;;)
    	            {
    	                int alt4=2;
    	        	{
    	        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	        	    */
    	        	    int LA4_0 = LA(1);
    	        	    if ( (((LA4_0 >= '0') && (LA4_0 <= '9'))) ) 
    	        	    {
    	        	        alt4=1;
    	        	    }

    	        	}
    	        	switch (alt4) 
    	        	{
    	        	    case 1:
    	        	        // ubibind.g:262:12: '0' .. '9'
    	        	        {
    	        	            MATCHRANGE('0', '9'); 
    	        	            if  (HASEXCEPTION())
    	        	            {
    	        	                goto ruleREAL_LITERALEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:
    	        	    
    	        		if ( cnt4 >= 1 )
    	        		{
    	        		    goto loop4;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleREAL_LITERALEx;
    	        	}
    	        	cnt4++;
    	            }
    	            loop4: ;	/* Jump to here if this rule does not match */
    	        }

    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleREAL_LITERALEx; /* Prevent compiler warnings */
    ruleREAL_LITERALEx: ;

}
// $ANTLR end REAL_LITERAL

//   Comes from: 266:5: ( '\\'' ( ESCAPE_SEQUENCE | ~ ( '\\'' | '\\\\' ) ) '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHARACTER_LITERAL
 *
 * Looks to match the characters the constitute the token CHARACTER_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHARACTER_LITERAL(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHARACTER_LITERAL;
       
    
    // ubibind.g:266:5: ( '\\'' ( ESCAPE_SEQUENCE | ~ ( '\\'' | '\\\\' ) ) '\\'' )
    // ubibind.g:266:9: '\\'' ( ESCAPE_SEQUENCE | ~ ( '\\'' | '\\\\' ) ) '\\''
    {
        MATCHC('\''); 
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }


        // ubibind.g:266:14: ( ESCAPE_SEQUENCE | ~ ( '\\'' | '\\\\' ) )
        {
            int alt6=2;

            {
                int LA6_0 = LA(1);
                if ( (LA6_0 == '\\') ) 
                {
                    alt6=1;
                }
                else if ( (((LA6_0 >= 0x0000) && (LA6_0 <= '&')) || ((LA6_0 >= '(') && (LA6_0 <= '[')) || ((LA6_0 >= ']') && (LA6_0 <= 0xFFFF))) ) 
                {
                    alt6=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 6;
                    EXCEPTION->state        = 0;


                    goto ruleCHARACTER_LITERALEx;
                }
            }
            switch (alt6) 
            {
        	case 1:
        	    // ubibind.g:266:16: ESCAPE_SEQUENCE
        	    {
        	        /* 266:16: ESCAPE_SEQUENCE */
        	        mESCAPE_SEQUENCE(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCHARACTER_LITERALEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // ubibind.g:266:34: ~ ( '\\'' | '\\\\' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '&')) || ((LA(1) >= '(') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleCHARACTER_LITERALEx;
        	        }


        	    }
        	    break;

            }
        }
        MATCHC('\''); 
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCHARACTER_LITERALEx; /* Prevent compiler warnings */
    ruleCHARACTER_LITERALEx: ;

}
// $ANTLR end CHARACTER_LITERAL

//   Comes from: 273:5: ( '\"' ( ESCAPE_SEQUENCE | ~ ( '\\\\' | '\"' ) )* '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_LITERAL
 *
 * Looks to match the characters the constitute the token STRING_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_LITERAL(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;
    const char* ret = NULL;


    _type	    = STRING_LITERAL;
       
    
    // ubibind.g:273:5: ( '\"' ( ESCAPE_SEQUENCE | ~ ( '\\\\' | '\"' ) )* '\"' )
    // ubibind.g:273:8: '\"' ( ESCAPE_SEQUENCE | ~ ( '\\\\' | '\"' ) )* '\"'
    {
        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


        // ubibind.g:273:12: ( ESCAPE_SEQUENCE | ~ ( '\\\\' | '\"' ) )*

        for (;;)
        {
            int alt7=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA7_0 = LA(1);
                if ( (LA7_0 == '\\') ) 
                {
                    alt7=1;
                }
                else if ( (((LA7_0 >= 0x0000) && (LA7_0 <= '!')) || ((LA7_0 >= '#') && (LA7_0 <= '[')) || ((LA7_0 >= ']') && (LA7_0 <= 0xFFFF))) ) 
                {
                    alt7=2;
                }

            }
            switch (alt7) 
            {
        	case 1:
        	    // ubibind.g:273:14: ESCAPE_SEQUENCE
        	    {
        	        /* 273:14: ESCAPE_SEQUENCE */
        	        mESCAPE_SEQUENCE(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRING_LITERALEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // ubibind.g:273:32: ~ ( '\\\\' | '\"' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleSTRING_LITERALEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop7;	/* break out of the loop */
        	    break;
            }
        }
        loop7: ; /* Jump out to here if this rule does not match */

        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSTRING_LITERALEx; /* Prevent compiler warnings */
    ruleSTRING_LITERALEx: ;

}
// $ANTLR end STRING_LITERAL

//   Comes from: 288:4: ( 'true' | 'false' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BOOLEAN_LITERAL
 *
 * Looks to match the characters the constitute the token BOOLEAN_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBOOLEAN_LITERAL(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BOOLEAN_LITERAL;
       
    
    {
        //  ubibind.g:288:4: ( 'true' | 'false' )
        
        ANTLR3_UINT32 alt8;

        alt8=2;


        {
            int LA8_0 = LA(1);
            if ( (LA8_0 == 't') ) 
            {
                alt8=1;
            }
            else if ( (LA8_0 == 'f') ) 
            {
                alt8=2;
            }
            else 
            {
            
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto ruleBOOLEAN_LITERALEx;
            }
        }
        switch (alt8) 
        {
    	case 1:
    	    // ubibind.g:288:6: 'true'
    	    {
    	        MATCHS(lit_6); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleBOOLEAN_LITERALEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // ubibind.g:288:15: 'false'
    	    {
    	        MATCHS(lit_7); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleBOOLEAN_LITERALEx;
    	        }



    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBOOLEAN_LITERALEx; /* Prevent compiler warnings */
    ruleBOOLEAN_LITERALEx: ;

}
// $ANTLR end BOOLEAN_LITERAL

//   Comes from: 293:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ESCAPE_SEQUENCE
 *
 * Looks to match the characters the constitute the token ESCAPE_SEQUENCE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mESCAPE_SEQUENCE(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // ubibind.g:293:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
    // ubibind.g:293:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
    {
        MATCHC('\\'); 
        if  (HASEXCEPTION())
        {
            goto ruleESCAPE_SEQUENCEEx;
        }

        if ( LA(1) == '"' || LA(1) == '\'' || LA(1) == '\\' || LA(1) == 'b' || LA(1) == 'f' || LA(1) == 'n' || LA(1) == 'r' || LA(1) == 't' )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleESCAPE_SEQUENCEEx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleESCAPE_SEQUENCEEx; /* Prevent compiler warnings */
    ruleESCAPE_SEQUENCEEx: ;

}
// $ANTLR end ESCAPE_SEQUENCE

//   Comes from: 297:4: ( LETTER ( LETTER | DIGIT | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IDENTIFIER
 *
 * Looks to match the characters the constitute the token IDENTIFIER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIDENTIFIER(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IDENTIFIER;
       
    
    // ubibind.g:297:4: ( LETTER ( LETTER | DIGIT | '_' )* )
    // ubibind.g:297:7: LETTER ( LETTER | DIGIT | '_' )*
    {
        /* 297:7: LETTER ( LETTER | DIGIT | '_' )* */
        mLETTER(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleIDENTIFIEREx;
        }


        // ubibind.g:297:14: ( LETTER | DIGIT | '_' )*

        for (;;)
        {
            int alt9=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA9_0 = LA(1);
                if ( (((LA9_0 >= '0') && (LA9_0 <= '9')) || ((LA9_0 >= 'A') && (LA9_0 <= 'Z')) || LA9_0 == '_' || ((LA9_0 >= 'a') && (LA9_0 <= 'z'))) ) 
                {
                    alt9=1;
                }

            }
            switch (alt9) 
            {
        	case 1:
        	    // ubibind.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleIDENTIFIEREx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop9;	/* break out of the loop */
        	    break;
            }
        }
        loop9: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleIDENTIFIEREx; /* Prevent compiler warnings */
    ruleIDENTIFIEREx: ;

}
// $ANTLR end IDENTIFIER

//   Comes from: 301:5: ( '%{' ( options {greedy=false; } : . )* '%}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RAW_DEFINITION
 *
 * Looks to match the characters the constitute the token RAW_DEFINITION
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRAW_DEFINITION(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RAW_DEFINITION;
       
    
    // ubibind.g:301:5: ( '%{' ( options {greedy=false; } : . )* '%}' )
    // ubibind.g:301:9: '%{' ( options {greedy=false; } : . )* '%}'
    {
        MATCHS(lit_8); 
        if  (HASEXCEPTION())
        {
            goto ruleRAW_DEFINITIONEx;
        }



        // ubibind.g:301:14: ( options {greedy=false; } : . )*

        for (;;)
        {
            int alt10=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA10_0 = LA(1);
                if ( (LA10_0 == '%') ) 
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA10_1 = LA(2);
                        if ( (LA10_1 == '}') ) 
                        {
                            alt10=2;
                        }
                        else if ( (((LA10_1 >= 0x0000) && (LA10_1 <= '|')) || ((LA10_1 >= '~') && (LA10_1 <= 0xFFFF))) ) 
                        {
                            alt10=1;
                        }

                    }
                }
                else if ( (((LA10_0 >= 0x0000) && (LA10_0 <= '$')) || ((LA10_0 >= '&') && (LA10_0 <= 0xFFFF))) ) 
                {
                    alt10=1;
                }

            }
            switch (alt10) 
            {
        	case 1:
        	    // ubibind.g:301:42: .
        	    {
        	        MATCHANY(); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleRAW_DEFINITIONEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop10;	/* break out of the loop */
        	    break;
            }
        }
        loop10: ; /* Jump out to here if this rule does not match */

        MATCHS(lit_9); 
        if  (HASEXCEPTION())
        {
            goto ruleRAW_DEFINITIONEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleRAW_DEFINITIONEx; /* Prevent compiler warnings */
    ruleRAW_DEFINITIONEx: ;

}
// $ANTLR end RAW_DEFINITION

//   Comes from: 305:7: ( 'a' .. 'z' | 'A' .. 'Z' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LETTER
 *
 * Looks to match the characters the constitute the token LETTER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLETTER(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // ubibind.g:305:7: ( 'a' .. 'z' | 'A' .. 'Z' )
    // ubibind.g:
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleLETTEREx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleLETTEREx; /* Prevent compiler warnings */
    ruleLETTEREx: ;

}
// $ANTLR end LETTER

//   Comes from: 308:7: ( '0' .. '9' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIGIT
 *
 * Looks to match the characters the constitute the token DIGIT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIGIT(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // ubibind.g:308:7: ( '0' .. '9' )
    // ubibind.g:308:9: '0' .. '9'
    {
        MATCHRANGE('0', '9'); 
        if  (HASEXCEPTION())
        {
            goto ruleDIGITEx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleDIGITEx; /* Prevent compiler warnings */
    ruleDIGITEx: ;

}
// $ANTLR end DIGIT

//   Comes from: 310:5: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;
       
    
    // ubibind.g:310:5: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
    // ubibind.g:310:8: ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || ((LA(1) >= '\f') && (LA(1) <= '\r')) || LA(1) == ' ' )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleWSEx;
        }

        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

//   Comes from: 314:5: ( '/*' ( options {greedy=false; } : . )* '*/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMENT
 *
 * Looks to match the characters the constitute the token COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMENT(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMENT;
       
    
    // ubibind.g:314:5: ( '/*' ( options {greedy=false; } : . )* '*/' )
    // ubibind.g:314:9: '/*' ( options {greedy=false; } : . )* '*/'
    {
        MATCHS(lit_10); 
        if  (HASEXCEPTION())
        {
            goto ruleCOMMENTEx;
        }



        // ubibind.g:314:14: ( options {greedy=false; } : . )*

        for (;;)
        {
            int alt11=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA11_0 = LA(1);
                if ( (LA11_0 == '*') ) 
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA11_1 = LA(2);
                        if ( (LA11_1 == '/') ) 
                        {
                            alt11=2;
                        }
                        else if ( (((LA11_1 >= 0x0000) && (LA11_1 <= '.')) || ((LA11_1 >= '0') && (LA11_1 <= 0xFFFF))) ) 
                        {
                            alt11=1;
                        }

                    }
                }
                else if ( (((LA11_0 >= 0x0000) && (LA11_0 <= ')')) || ((LA11_0 >= '+') && (LA11_0 <= 0xFFFF))) ) 
                {
                    alt11=1;
                }

            }
            switch (alt11) 
            {
        	case 1:
        	    // ubibind.g:314:42: .
        	    {
        	        MATCHANY(); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCOMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop11;	/* break out of the loop */
        	    break;
            }
        }
        loop11: ; /* Jump out to here if this rule does not match */

        MATCHS(lit_11); 
        if  (HASEXCEPTION())
        {
            goto ruleCOMMENTEx;
        }


        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOMMENTEx; /* Prevent compiler warnings */
    ruleCOMMENTEx: ;

}
// $ANTLR end COMMENT

//   Comes from: 318:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LINE_COMMENT
 *
 * Looks to match the characters the constitute the token LINE_COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLINE_COMMENT(pubibindLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LINE_COMMENT;
       
    
    // ubibind.g:318:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' )
    // ubibind.g:318:7: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
    {
        MATCHS(lit_12); 
        if  (HASEXCEPTION())
        {
            goto ruleLINE_COMMENTEx;
        }



        // ubibind.g:318:12: (~ ( '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt12=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA12_0 = LA(1);
                if ( (((LA12_0 >= 0x0000) && (LA12_0 <= '\t')) || ((LA12_0 >= 0x000B) && (LA12_0 <= '\f')) || ((LA12_0 >= 0x000E) && (LA12_0 <= 0xFFFF))) ) 
                {
                    alt12=1;
                }

            }
            switch (alt12) 
            {
        	case 1:
        	    // ubibind.g:318:12: ~ ( '\\n' | '\\r' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleLINE_COMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop12;	/* break out of the loop */
        	    break;
            }
        }
        loop12: ; /* Jump out to here if this rule does not match */


        // ubibind.g:318:26: ( '\\r' )?
        {
            int alt13=2;
            {
                int LA13_0 = LA(1);
                if ( (LA13_0 == '\r') ) 
                {
                    alt13=1;
                }
            }
            switch (alt13) 
            {
        	case 1:
        	    // ubibind.g:318:26: '\\r'
        	    {
        	        MATCHC('\r'); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleLINE_COMMENTEx;
        	        }


        	    }
        	    break;

            }
        }
        MATCHC('\n'); 
        if  (HASEXCEPTION())
        {
            goto ruleLINE_COMMENTEx;
        }

        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLINE_COMMENTEx; /* Prevent compiler warnings */
    ruleLINE_COMMENTEx: ;

}
// $ANTLR end LINE_COMMENT

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(pubibindLexer ctx)
{
    {
        //  ubibind.g:1:8: ( T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | INTEGER_LITERAL | REAL_LITERAL | CHARACTER_LITERAL | STRING_LITERAL | BOOLEAN_LITERAL | IDENTIFIER | RAW_DEFINITION | WS | COMMENT | LINE_COMMENT )
        
        ANTLR3_UINT32 alt14;

        alt14=21;

        alt14 = cdfa14.predict(ctx, RECOGNIZER, ISTREAM, &cdfa14);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt14) 
        {
    	case 1:
    	    // ubibind.g:1:10: T__17
    	    {
    	        /* 1:10: T__17 */
    	        mT__17(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // ubibind.g:1:16: T__18
    	    {
    	        /* 1:16: T__18 */
    	        mT__18(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // ubibind.g:1:22: T__19
    	    {
    	        /* 1:22: T__19 */
    	        mT__19(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // ubibind.g:1:28: T__20
    	    {
    	        /* 1:28: T__20 */
    	        mT__20(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // ubibind.g:1:34: T__21
    	    {
    	        /* 1:34: T__21 */
    	        mT__21(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // ubibind.g:1:40: T__22
    	    {
    	        /* 1:40: T__22 */
    	        mT__22(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // ubibind.g:1:46: T__23
    	    {
    	        /* 1:46: T__23 */
    	        mT__23(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // ubibind.g:1:52: T__24
    	    {
    	        /* 1:52: T__24 */
    	        mT__24(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // ubibind.g:1:58: T__25
    	    {
    	        /* 1:58: T__25 */
    	        mT__25(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // ubibind.g:1:64: T__26
    	    {
    	        /* 1:64: T__26 */
    	        mT__26(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // ubibind.g:1:70: T__27
    	    {
    	        /* 1:70: T__27 */
    	        mT__27(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // ubibind.g:1:76: INTEGER_LITERAL
    	    {
    	        /* 1:76: INTEGER_LITERAL */
    	        mINTEGER_LITERAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // ubibind.g:1:92: REAL_LITERAL
    	    {
    	        /* 1:92: REAL_LITERAL */
    	        mREAL_LITERAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // ubibind.g:1:105: CHARACTER_LITERAL
    	    {
    	        /* 1:105: CHARACTER_LITERAL */
    	        mCHARACTER_LITERAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // ubibind.g:1:123: STRING_LITERAL
    	    {
    	        /* 1:123: STRING_LITERAL */
    	        mSTRING_LITERAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // ubibind.g:1:138: BOOLEAN_LITERAL
    	    {
    	        /* 1:138: BOOLEAN_LITERAL */
    	        mBOOLEAN_LITERAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // ubibind.g:1:154: IDENTIFIER
    	    {
    	        /* 1:154: IDENTIFIER */
    	        mIDENTIFIER(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // ubibind.g:1:165: RAW_DEFINITION
    	    {
    	        /* 1:165: RAW_DEFINITION */
    	        mRAW_DEFINITION(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // ubibind.g:1:180: WS
    	    {
    	        /* 1:180: WS */
    	        mWS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // ubibind.g:1:183: COMMENT
    	    {
    	        /* 1:183: COMMENT */
    	        mCOMMENT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // ubibind.g:1:191: LINE_COMMENT
    	    {
    	        /* 1:191: LINE_COMMENT */
    	        mLINE_COMMENT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
